apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql-0 # Storage path on the node for mysql-0
  claimRef:
    namespace: default
    name: mysql-storage-mysql-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql-1 # Storage path on the node for mysql-1
  claimRef:
    namespace: default
    name: mysql-storage-mysql-1
