apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce #So that only one pod can write to volume
  hostPath:
    path: /mnt/data/mongodb-0 # Storage path on the node for mongodb-0
  claimRef: # Pre-bind this PV to the PVC
    namespace: default
    name: mongodb-storage-mongodb-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mongodb-1 # Storage path on the node for mongodb-1
  claimRef: # Pre-bind this PV to the PVC
    namespace: default
    name: mongodb-storage-mongodb-1
