apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  serviceName: "mongodb-service" # Headless service
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        command:
        - "mongod"
        - "--replSet"
        - "rs0"
        - "--bind_ip_all"
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db # Mounting PVCs dynamically
  volumeClaimTemplates:
  - metadata:
      name: mongodb-storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi # Matches the pre-created PVs
      selector:
        matchLabels:
          type: mongodb-storage # Match the labels on the existing PVs to match pvc-pv
