apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  clusterIP: None # This makes the service headless
  selector:
    app: mongodb
  ports:
  - name: mongo
    port: 27017 # MongoDB default port
    targetPort: 27017
